#! /bin/sh
### BEGIN INIT INFO
# Provides:          rest_sensor.py
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start the smart plant sensor
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions
# If you need to source some other scripts, do it here

case "$1" in
  start)
    echo "Starting script" >> /home/pi/code/BDAAS/pi/startup.log
    python /home/pi/code/BDAAS/pi/rest_sensor.py
    echo $? >> /home/pi/code/BDAAS/pi/startup.log
    exit 0
    ;;
  stop)
    log_begin_msg "stopping sensor service"
    echo "Starting sensor service" >> /home/pi/code/BDAAS/pi/startup.log

    log_end_msg $?
    exit 0
    ;;
  *)
    echo "Usage: /etc/init.d/<your script> {start|stop}"
    exit 1
    ;;
esac